### ISSUE TITLE
Promises - howto

### ISSUE THREAD

**Issue by azappa** [prismicio/express-prismic#5]
Using new nodejs-kit and the new method with Promises this is an example route

``` javascript
exports.index = function (req, res) {

  var p = prismic.withContext(req,res);

  p.query(
    [
      prismic.Predicates.at("document.type", "slider")
    ],
    { pageSize : 10 },
    function (err, slider) {
      console.log(slider);
      res.render('index');  
    }
  );

};
```

Is there a way to do things like this:

``` javascript
var p = prismic.withContext(req,res);  
var slider = p.query([ prismic.Predicates.at("document.type", "slider") ], { pageSize : 10 });
//  -- other variables like the row before this comment
res.render('index', {slider: slider});
```

?

Thank you!

**Comment by erwan** [comment]
Hi Alessio,

We're using Promises internally but since ES6 promises are not in standard in Node.js we're not exposing them. We're using the usual function(err, result) callbacks, but you can wrap that in whatever promises you like (q.js or other).

It wouldn't be the syntax you're showing because you wouldn't pass a promise to your view, but you can wrap all your calls in promises and do a Promise.all (or Q.all, or other depending on your lib) to wait for the completion of all the promises.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by azappa** [comment]
Whoops, ok, thank you! So the old method I used with async.parallel (or some Promise lib as you said) still working? Good to know!
